import { Plant } from '../entities/Plant';

export const plants: Plant[] = [
    {
        id: 1,
        name: 'Aloe Vera',
        description: 'A succulent plant species of the genus Aloe.',
        careInstructions: 'Water deeply but infrequently, and place in bright, indirect light.',
        photoUrl: 'gs://plantmingle.appspot.com/Aloe-Vera-Plant-2.jpg',
        ownerId: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 2,
        name: 'Snake Plant',
        description: 'A species of flowering plant in the family Asparagaceae.',
        careInstructions: 'Water every 2-8 weeks and place in indirect light.',
        photoUrl: 'gs://plantmingle.appspot.com/snake-plant.jpg',
        ownerId: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 3,
        name: 'Peace Lily',
        description: 'A genus of flowering plants in the family Araceae.',
        careInstructions: 'Keep soil consistently moist but not soggy, and place in low to medium light.',
        photoUrl: 'backend/src/mockData/flower.png',
        ownerId: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        name: 'Fiddle Leaf Fig',
        description: 'A species of flowering plant in the mulberry family.',
        careInstructions: 'Water when the top inch of soil feels dry, and place in bright, indirect light.',
        photoUrl: 'backend/src/mockData/flower.png',
        ownerId: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 5,
        name: 'Spider Plant',
        description: 'A species of perennial flowering plants in the family Asparagaceae.',
        careInstructions: 'Keep soil evenly moist but not soggy, and place in bright, indirect light.',
        photoUrl: 'backend/src/mockData/flower.png',
        ownerId: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 6,
        name: 'Rubber Plant',
        description: 'A species of plant in the fig genus, native to eastern parts of South Asia and southeast Asia.',
        careInstructions: 'Allow soil to dry out slightly between watering, and place in bright, indirect light.',
        photoUrl: 'backend/src/mockData/flower.png',
        ownerId: 6,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 7,
        name: 'Monstera Deliciosa',
        description: 'A species of flowering plant native to tropical forests of southern Mexico, south to Panama.',
        careInstructions: 'Water when the top inch of soil feels dry, and place in bright, indirect light.',
        photoUrl: 'backend/src/mockData/flower.png',
        ownerId: 7,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 8,
        name: 'Pothos',
        description: 'A genus of flowering plants in the family Araceae.',
        careInstructions: 'Allow soil to dry out slightly between watering, and place in bright, indirect light.',
        photoUrl: 'backend/src/mockData/flower.png',
        ownerId: 8,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 9,
        name: 'English Ivy',
        description: 'A species of flowering plant in the family Araliaceae.',
        careInstructions: 'Keep soil consistently moist but not soggy, and place in bright, indirect light.',
        photoUrl: 'backend/src/mockData/flower.png',
        ownerId: 9,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 10,
        name: 'ZZ Plant',
        description: 'A species of plant in the family Araceae.',
        careInstructions: 'Allow soil to dry out completely between watering, and place in low to bright, indirect light.',
        photoUrl: 'backend/src/mockData/flower.png',
        ownerId: 10,
        created_at: new Date(),
        updated_at: new Date(),
    },
];
