import {User} from "../entities/User";

export const users: User[] = [
    {
        id: 1,
        username: 'johndoe',
        email: 'john.doe@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Gardening enthusiast.',
        profilePictureUrl: 'http://example.com/johndoe.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 2,
        username: 'janedoe',
        email: 'jane.doe@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Love plants and sharing them!',
        profilePictureUrl: 'http://example.com/janedoe.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 3,
        username: 'michaelsmith',
        email: 'michael.smith@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Gardener with a love for succulents.',
        profilePictureUrl: 'http://example.com/michaelsmith.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        username: 'emilyjohnson',
        email: 'emily.johnson@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Herb gardener and plant swapper.',
        profilePictureUrl: 'http://example.com/emilyjohnson.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 5,
        username: 'davidthomas',
        email: 'david.thomas@example.com',
        password: 'hashedpassword',
        location: 'Modřice',  // Nearby Brno
        bio: 'Love urban gardening and sharing plants.',
        profilePictureUrl: 'http://example.com/davidthomas.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 6,
        username: 'sarahwilson',
        email: 'sarah.wilson@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Balcony gardener with a variety of flowers.',
        profilePictureUrl: 'http://example.com/sarahwilson.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 7,
        username: 'jamesmoore',
        email: 'james.moore@example.com',
        password: 'hashedpassword',
        location: 'Šlapanice',  // Nearby Brno
        bio: 'Sharing my plant collection with fellow enthusiasts.',
        profilePictureUrl: 'http://example.com/jamesmoore.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 8,
        username: 'laurabrown',
        email: 'laura.brown@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Indoor plant lover and swapper.',
        profilePictureUrl: 'http://example.com/laurabrown.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 9,
        username: 'chrismiller',
        email: 'chris.miller@example.com',
        password: 'hashedpassword',
        location: 'Kuřim',  // Nearby Brno
        bio: 'Passionate about growing and sharing plants.',
        profilePictureUrl: 'http://example.com/chrismiller.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 10,
        username: 'oliviadavis',
        email: 'olivia.davis@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Garden enthusiast with a focus on rare plants.',
        profilePictureUrl: 'http://example.com/oliviadavis.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },   
];