import { User, Plant, Match } from '@prisma/client';

export const users: User[] = [
    {
        id: 1,
        username: 'johndoe',
        email: 'john.doe@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Gardening enthusiast.',
        profilePictureUrl: 'http://example.com/johndoe.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 2,
        username: 'janedoe',
        email: 'jane.doe@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Love plants and sharing them!',
        profilePictureUrl: 'http://example.com/janedoe.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 3,
        username: 'michaelsmith',
        email: 'michael.smith@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Gardener with a love for succulents.',
        profilePictureUrl: 'http://example.com/michaelsmith.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        username: 'emilyjohnson',
        email: 'emily.johnson@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Herb gardener and plant swapper.',
        profilePictureUrl: 'http://example.com/emilyjohnson.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 5,
        username: 'davidthomas',
        email: 'david.thomas@example.com',
        password: 'hashedpassword',
        location: 'Modřice',  // Nearby Brno
        bio: 'Love urban gardening and sharing plants.',
        profilePictureUrl: 'http://example.com/davidthomas.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 6,
        username: 'sarahwilson',
        email: 'sarah.wilson@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Balcony gardener with a variety of flowers.',
        profilePictureUrl: 'http://example.com/sarahwilson.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 7,
        username: 'jamesmoore',
        email: 'james.moore@example.com',
        password: 'hashedpassword',
        location: 'Šlapanice',  // Nearby Brno
        bio: 'Sharing my plant collection with fellow enthusiasts.',
        profilePictureUrl: 'http://example.com/jamesmoore.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 8,
        username: 'laurabrown',
        email: 'laura.brown@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Indoor plant lover and swapper.',
        profilePictureUrl: 'http://example.com/laurabrown.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 9,
        username: 'chrismiller',
        email: 'chris.miller@example.com',
        password: 'hashedpassword',
        location: 'Kuřim',  // Nearby Brno
        bio: 'Passionate about growing and sharing plants.',
        profilePictureUrl: 'http://example.com/chrismiller.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 10,
        username: 'oliviadavis',
        email: 'olivia.davis@example.com',
        password: 'hashedpassword',
        location: 'Brno',
        bio: 'Garden enthusiast with a focus on rare plants.',
        profilePictureUrl: 'http://example.com/oliviadavis.jpg',
        created_at: new Date(),
        updated_at: new Date(),
    },
];

export const plants: Plant[] = [
    {
        id: 1,
        name: 'Aloe Vera',
        description: 'The Aloe Vera is a stemless succulent with thick and fleshy leaves that are lined with small teeth making it a great ornamental, low maintenance indoor plant which blooms a yellow tubular flower in the summertime. Native to the Arabian Peninsula, this plant is widely used around the world as its leaves are considered to be antimicrobial and has been used to treat burns as a topical medication.',
        careInstructions: 'Water deeply but infrequently, and place in bright, indirect light.',
        photoUrl: 'gs://plantmingle.appspot.com/Aloe-Vera-Plant-2.jpg',
        ownerId: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 2,
        name: "Snake Plant 'Laurentii'",
        description: 'This evergreen perennial native to tropical West Africa and Nigeria, is a great addition to any office or household as a natural air purifier. Snake plants have strong and sturdy, sword shaped leaves which are drought tolerant and retains the plants water. This plant can be easily propagated by leaf cuttings so you can multiply your family of snake plants or give them away as a gift. This particular variety has a washed out greyish-green look on the entirety of the plant making this a very unique addition to any plant collection.',
        careInstructions: 'Water every 2-8 weeks and place in indirect light.',
        photoUrl: 'gs://plantmingle.appspot.com/snake-plant.jpg',
        ownerId: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 3,
        name: "Spathiphyllum 'Peace Lily'",
        description: 'This evergreen perennial is a popular flowering houseplant native to tropical Southeastern Asia. Also a known air purifier, this plant is a great addition to any office, home, or desk space as it is easy to care for and does not require too much sunlight. The Peace lily will reward you with a beautiful folded flower a few times each year.',
        careInstructions: 'Keep soil consistently moist but not soggy, and place in low to medium light.',
        photoUrl: "gs://plantmingle.appspot.com/Spathiphyllum 'Peace Lily'2.jpg",
        ownerId: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        name: "Ficus Lyrata 'Fiddle Leaf Fig'",
        description: 'Native to tropical western Africa, Ficus lyrata, commonly known as the fiddle-leaf fig, has green, leathery and shiny and have distinctive, pale veins. These veins are embedded in the violin-shaped leaves. Although Ficus lyrata grows naturally in lowland tropical forests it can thrive in a large range of environments. Place in bright indirect sunlight, on the ground where it can grow up to 6 tall. Keep soil moist. Toxic to pets if ingested.',
        careInstructions: 'Water when the top inch of soil feels dry, and place in bright, indirect light.',
        photoUrl: "gs://plantmingle.appspot.com/Ficus Lyrata 'Fiddle Leaf Fig'2.jpg",
        ownerId: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 5,
        name: "Spider Plant 'Bonnie'",
        description: "The Spider plant is a flowering perennial native tropical South Africa. The leaves of the spider plant are thin ribbon like strands which end in a point and grow upward and bend downward giving it the look of a spider. The Spider plant produces small white flowers that grow along a long stalk independent to the leaves of the spider plant. Also known for their air purifying qualities, the spider plant is a great companion to any household of office.",
        careInstructions: 'Keep soil evenly moist but not soggy, and place in bright, indirect light.',
        photoUrl: "gs://plantmingle.appspot.com/Spider Plant 'Bonnie'2.jpg",
        ownerId: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 6,
        name: "Ficus Elastica 'Ruby Pink'",
        description: "Native to tropical regions of India and Malaysia, Ficus Ruby Pink is a hardy, vibrant evergreen plant with red-pink and white variegation. Care is similar to other rubber plants, but the variegation requires more light than the 'Burgundy' variety. It won't do well in low light spaces, so place in bright indirect light. Water to keep soil moist at all times. Ficus elastica is a source of latex that is toxic to the skin, and poisonous if ingested, so pet-owners and those allergic to latex should be cautious.",
        careInstructions: 'Allow soil to dry out slightly between watering, and place in bright, indirect light.',
        photoUrl: "gs://plantmingle.appspot.com/Ficus Elastica 'Ruby Pink'2.jpg",
        ownerId: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 7,
        name: "Monstera 'Thai Constellation'",
        description: "Monstera Thai Constellation is a rare but fast-growing plant from the Monstera Deliciosa family. This monstera has plenty of heavenly splatters and splotches of creamy or off-white against their green leaves. It almost looks like the night sky with stars. ",
        careInstructions: 'Water when the top inch of soil feels dry, and place in bright, indirect light.',
        photoUrl: "gs://plantmingle.appspot.com/Monstera 'Thai Constellation'.jpg",
        ownerId: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 8,
        name: "Pothos 'Neon'",
        description: "An electrifying color variation on the standard Pothos. ‘Neon’ has all of the tough, reliable features houseplant lovers have come to expect from Pothos, but with glowing, neon-green foliage. Place where the vines can fall freely or trail along a shelf for the best effect. Looks great grown in containers and hanging baskets. A terrific plant for tall plant stands where the trailing foliage will create a cascade of foliage over time.",
        careInstructions: 'Allow soil to dry out slightly between watering, and place in bright, indirect light.',
        photoUrl: "gs://plantmingle.appspot.com/Pothos 'Neon'.jpg",
        ownerId: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 9,
        name: "English Ivy 'Glacier'",
        description: "Foliage bears a rich, emerald green coloring with high contrast, creamy white margins. A fast growing vine that roots as it travels, or climbs with clinging rootlets onto any vertical surface. One of the best choices for a fast-growing arrangement or ground cover.",
        careInstructions: 'Keep soil consistently moist but not soggy, and place in bright, indirect light.',
        photoUrl: "gs://plantmingle.appspot.com/English Ivy 'Glacier'.jpg",
        ownerId: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 10,
        name: "ZZ Plant",
        description: "Zamioculcas Zamiifolia also known as the ZZ Plant adds to any interior space with its unique growth pattern. Its low water requirements and drought tolerance handle well in many environments. (dry and humid) The drought-tolerant ZZ plant is a wonderful addition to low-light situations in homes and offices, but all parts of this plant are poisonous. Keep it away from children and pets.",
        careInstructions: 'Allow soil to dry out completely between watering, and place in low to bright, indirect light.',
        photoUrl: "gs://plantmingle.appspot.com/Zamioculcas Zamiifolia 'ZZ'.jpg",
        ownerId: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
];

export const matches: Match[] = [
    {
        id: 1,
        userId1: 1,
        userId2: 2,
        plantId1: 1,
        plantId2: 2,
        matched_at: new Date(),
    },
];
