kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plantmingle-fe-pvc-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
