kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plantmingle-fe-pvc-nginx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
